#                                                                        #
# Default subroutes configuration for the TYPO3CR package                #
#                                                                        #

# $Id$

##
# Routes definitions for the services

--
  name: 'service with controller and id'
  uriPattern: '/service/v1/{@controller}/{id}'
  defaults: 
    @package:    'TYPO3CR'
    @subpackage: 'Admin\Service'
    @format:     'json'

--
  name: 'service with controller'
  uriPattern: '/service/v1/{@controller}'
  defaults:
    @package:    'TYPO3CR'
    @subpackage: 'Admin\Service'
    @format:     'json'

##
# TYPO3CR default routes

--
  name: 'default with controller and action'
  uriPattern: '/{@controller}/{@action}'
  defaults:
    @package:    'TYPO3CR'
    @subpackage: 'Admin'

--
  name: 'default with controller'
  uriPattern: '/{@controller}'
  defaults:
    @package:    'TYPO3CR'
    @subpackage: 'Admin'
    @action:     'index'

--
  name: 'fallback'
  uriPattern: ''
  defaults:
    @package:    'TYPO3CR'
    @subpackage: 'Admin'
    @controller: 'Standard'
    @action:     'index'
