#                                                                        #
# Default routes configuration for the TYPO3CR package                   #
#                                                                        #

# $Id$

##
# TYPO3CR route with optional controller

#TYPO3CR:
#  uriPattern: 'typo3cr(/{@controller})'
#  defaults:
#    @package:    'TYPO3CR'
#    @subpackage: 'Admin'
#    @controller: 'Default'
#    @action:     'index'
#    @format:     'html'

##
# TYPO3CR route with controller and optional action

#TYPO3CR_WithControllerAndOptionalAction:
#  uriPattern: 'typo3cr/{@controller}(/{@action})'
#  defaults:
#    @package:    'TYPO3CR'
#    @subpackage: 'Admin'
#    @action:     'index'
#    @format:     'html'

##
# Routes definitions for the services

#TYPO3CR_ServiceWithController:
#  uriPattern: 'typo3cr/service/v1/{@controller}'
#  defaults: 
#    @package:    'TYPO3CR'
#    @subpackage: 'Admin'
#    @format:     'json'

#TYPO3CR_ServiceWithControllerAndFormat:
#  uriPattern: 'typo3cr/service/v1/{@controller}.{@format}'
#  defaults: 
#    @package:    'TYPO3CR'
#    @subpackage: 'Admin'

#TYPO3CR_ServiceWithControllerAndIdAndOptionalFormat:
#  uriPattern: 'typo3cr/service/v1/{@controller}/{id}(.{@format})'
#  defaults: 
#    @package:    'TYPO3CR'
#    @subpackage: 'Admin'
#    @format:     'json'
