#                                                                        #
# Routes configuration for the TYPO3CR package                           #
#                                                                        #

# $Id$

TYPO3CR_Default:
  uriPattern: 'typo3cr/[@controller]/[@action]'
  controllerComponentNamePattern: 'F3::@package::Admin::Controller::@controllerController'
  viewComponentNamePattern: 'F3::@package::Admin::View::@controller@action@format'
  defaults:
    @package:    'TYPO3CR'
    @controller: 'Default'
    @action:     'index'
    @format:     'html'
